branches:
  only:
    - test-wasm

language: node_js
node_js:
  - node

sudo: required

before_install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt update
  - sudo apt install cmake -y

script:
  - ./build_wasm.sh
